# Generated by Django 5.1.7 on 2025-03-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menuitem_category_alter_menuitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/images'),
        ),
    ]
